In [40]:
import pandas as pd

In [41]:
istanze = pd.read_excel('istanza.xlsx')
result =pd.DataFrame({'opt': [], 'subopt': [],'opt_gap': [],'subopt_gap': [],'Err_ass_opt': [],'Err_ass_subopt': [], 'Time':[]})

In [42]:
for i in range(len(istanze)):
    df=pd.read_excel('result'+str(i)+'.xlsx')
    df.drop('n_items', axis =1, inplace=True)
    df1 =df[(df['Time'] < 300)]
    df2 =df[(df['Time'] >= 300)]
    
    opt = len(df1)
    opt_gap = sum(df1.apply(lambda x: (x.Eu_obj-x.Mod_obj)/x.Mod_obj, axis = 1)*100)/len(df1) if len(df1) != 0 else 0
    Err_ass_opt = sum(df1.apply(lambda x: (x.Eu_obj-x.Mod_obj), axis = 1))/len(df1) if len(df1) != 0 else 0
    Time = sum(df1.Time)/len(df) if len(df1) != 0 else 0


    subopt = len(df2)
    subopt_gap = sum(df2.apply(lambda x: (x.Eu_obj-x.Mod_obj)/x.Mod_obj, axis = 1)*100)/len(df2) if len(df2) != 0 else 0
    Err_ass_subopt = sum(df2.apply(lambda x: (x.Eu_obj-x.Mod_obj), axis = 1))/len(df2) if len(df2) != 0 else 0
    
    opt_gap = abs(round(opt_gap,2))
    Err_ass_opt = abs(round(Err_ass_opt,2))
    Time = abs(round(Time,2))


    subopt_gap = abs(round(subopt_gap,2))
    Err_ass_subopt = abs(round(Err_ass_subopt,2))

    
    result=result.append(pd.DataFrame({'opt': [opt], 'subopt': [subopt],'opt_gap': [opt_gap],'subopt_gap': [subopt_gap],'Err_ass_opt': [Err_ass_opt],'Err_ass_subopt': [Err_ass_subopt], 'Time': [Time]}),ignore_index=True)

In [43]:
result

   Err_ass_opt  Err_ass_subopt   Time   opt  opt_gap  subopt  subopt_gap
0         0.23            0.59  26.21  64.0     3.89    36.0        7.35
1         0.81            1.48  23.00  73.0    11.90    27.0       15.98
2         0.10            0.17  15.02  76.0     0.94    24.0        0.91
3         1.26            2.62  16.62  84.0    12.29    16.0       17.26
4         0.00            0.00  20.77  75.0     0.00    25.0        0.00
5         0.11            0.21   9.18  73.0    14.17    27.0       16.16
6         0.48            1.63  13.29  77.0     6.68    23.0       18.55
7         0.00            0.00  27.83  76.0     0.00    24.0        0.00
8         0.00            0.00  19.19  81.0     0.00    19.0        0.00
9         0.45            1.10   8.59  81.0    10.34    19.0       20.58

In [7]:
result.to_excel('info_result.xlsx', encoding='utf8')